name: Generate

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # Every morning at 5am

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: mkdir skyf0l && npm --silent start > skyf0l/README.md

      - name: Commit changes
        run: |
          cd skyf0l
          git init
          git branch -m main
          git remote add origin https://skyf0l:${{ secrets.SKYF0L_PAT }}@github.com/skyf0l/skyf0l.git
          git add README.md
          git commit -m "Update README.md"
          git push -f origin main
